name: flutter_uploader_example
version: 1.2.0
description: Demonstrates how to use the flutter_uploader plugin.
publish_to: "none"

dependencies:
  crypto: ^2.1.4
  flutter:
    sdk: flutter
  file_picker: ^2.1.4
  path_provider: ^1.6.24
  image_picker: ^0.6.7+17
  shared_preferences: ^0.5.12+4
  flutter_local_notifications: ^3.0.2

dev_dependencies:
  integration_test: ^1.0.1
  flutter_test:
    sdk: flutter

  flutter_uploader:
    path: ../

flutter:
  uses-material-design: true
