name: flutter_uploader_example
version: 3.0.0-beta.1
description: Demonstrates how to use the flutter_uploader plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^3.0.0
  path_provider: ^2.0.1
  image_picker: ^0.7.3
  shared_preferences: ^2.0.5
  flutter_local_notifications: ^5.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_uploader:
    path: ../

flutter:
  uses-material-design: true
