name: flutter_uploader_example
version: 1.2.0
description: Demonstrates how to use the flutter_uploader plugin.
publish_to: "none"

dependencies:
  crypto: ^2.1.4
  flutter:
    sdk: flutter
  path_provider: ^1.6.11
  image_picker: ^0.6.7+4
  shared_preferences: ^0.5.8

dev_dependencies:
  e2e: ^0.6.1
  flutter_test:
    sdk: flutter

  flutter_uploader:
    path: ../

flutter:
  uses-material-design: true
