name: flutter_uploader
description: background upload plugin for flutter
version: 1.2.1
homepage: https://github.com/fluttercommunity/flutter_uploader
maintainer: Sebastian Roth (@ened)

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bluechilli.flutteruploader
        pluginClass: FlutterUploaderPlugin
      ios:
        pluginClass: FlutterUploaderPlugin