name: flutter_uploader
description: A plugin for creating and managing upload tasks with optional background exection support.
version: 2.0.0-beta.4
homepage: https://github.com/fluttercommunity/flutter_uploader
maintainer: Sebastian Roth (@ened)

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  equatable: ^1.2.5
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.0
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bluechilli.flutteruploader
        pluginClass: FlutterUploaderPlugin
      ios:
        pluginClass: FlutterUploaderPlugin
