name: flutter_uploader
description: A plugin for creating and managing upload tasks with optional background exection support.
version: 1.2.0
homepage: https://github.com/BlueChilli/flutter_uploader

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.0
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.bluechilli.flutteruploader
    pluginClass: FlutterUploaderPlugin
